# Generated by Django 3.2.9 on 2021-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(default='0', max_length=200)),
                ('deadline', models.DateTimeField()),
                ('materials', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
